### PR TITLE
Update cwe.py

### PR DESCRIPTION
**Pull request by grvkamath**
small fixes to make the CWE class compatible with Llama 2 models!

### CODE REVIEW

**Comment by kanishkamisra** [comment]
Hey thanks for noticing this and proposing a fix! I think the fix works, but was wondering if we should instead do the gpt2 thing only if the model is GPT2/GPT-neo/GPT-J? I think most models nowadays are more like llama so it might be better if we condition on presence of gpt rather than absence? Ff to make changes and re-submit, I'd for this to be your first PR haha :)

**Comment by grvkamath** [comment]
Hey, I've added more changes that should automate this process, i.e. classify a tokenizer as being more like the Llama tokenizers or more like the GPT2/Neo/J tokenizers. Lmk if you have any extra suggestions!

**Comment by kanishkamisra** [comment]
This is a brilliant solution! I like the idea of "inferring" the tokenizer behavior! Might even be useful when I eventually integrate tiago pimentel and clara meister's "proper way of computing word probabilities"! Thanks :D

**Comment by grvkamath** [comment]
Thanks so much!!! Glad you think it's a good fix. Let me know if any issues pop up with it!

**Pull request merged**
